from __future__ import annotations

import bpy

GENERATED_OBJECT_NAMES = {
    "Orthophoto",
    "TrackSurvey",
    "TrackRoad",
    "TrackRoad_Backup",
    "StartFinishLine",
}


GENERATED_OBJECT_PREFIXES = (
    "Orthophoto.",
    "TrackSurvey.",
    "TrackRoad.",
    "TrackRoad_Backup.",
    "StartFinishLine.",
    "SFLabel_",
)


def is_generated_object(
    obj: bpy.types.Object,
) -> bool:
    """
    Return True when the object is generated by KartSimDT.
    """

    if obj.name in GENERATED_OBJECT_NAMES:
        return True

    return obj.name.startswith(
        GENERATED_OBJECT_PREFIXES,
    )


def print_scene_objects(
    title: str,
) -> None:
    """Print current Blender scene objects."""

    print()
    print("=" * 60)
    print(title)
    print("=" * 60)

    for obj in bpy.context.scene.objects:
        print(
            f"{obj.name:30} "
            f"{obj.type:8} "
            f"hidden={obj.hide_viewport} "
            f"render={obj.hide_render}"
        )


def cleanup_scene() -> None:
    """
    Remove all KartSimDT generated objects.

    Persistent Blender infrastructure is preserved:

        Camera
        Light
    """

    print()
    print("=" * 60)
    print("KartSimDT Scene Cleanup")
    print("=" * 60)

    print_scene_objects(
        "SCENE BEFORE CLEANUP",
    )

    objects_to_remove = [
        obj for obj in list(bpy.data.objects) if is_generated_object(obj)
    ]

    print()
    print(f"Generated objects found : " f"{len(objects_to_remove)}")

    for obj in objects_to_remove:
        print(f"Removing               : " f"{obj.name} [{obj.type}]")

        bpy.data.objects.remove(
            obj,
            do_unlink=True,
        )

    bpy.ops.outliner.orphans_purge(
        do_local_ids=True,
        do_linked_ids=True,
        do_recursive=True,
    )

    print_scene_objects(
        "SCENE AFTER CLEANUP",
    )

    print()
    print("Scene cleanup complete.")
    print("=" * 60)
    print()
